apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: fanout
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /mms(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: mms
            port:
              number: 8080
